### PR TITLE
Encrypt EBS volumes using the default AWS/EBS key.

### PR DESCRIPTION
**Pull request by kensington**

### CODE REVIEW

**Comment by sormy** [comment]
What is the benefit of this change?

**Comment by kensington** [comment]
The benefit is that the volume is encrypted at rest, rather than stored in plaintext.

I could refactor this to be behind an option if that's preferred.

**Comment by sormy** [comment]
I guess users would like to provide their own encryption key rather than using hardcoded. Could we make it optional and use key provided from command line in case if user needs an encryption?

**Comment by sormy** [comment]
Default KmsKeyId is different per account, so it should be passed as env variable.
It could be good to have an explanation for the feature in README.

**Comment by sormy** [comment]
I'm closing this PR due to inactivity

**Pull request closed without merging**
